package provider

var Registry = []Provider{
	{
		ID:       "openai",
		Priority: 30,
		Alias:    "openai",
		Display:  Display{Name: "OpenAI", Icon: "auto_awesome", Color: "#10A37F", TextIcon: "OA", Website: "https://platform.openai.com", Notice: &Notice{APIKeyURL: "https://platform.openai.com/api-keys"}},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.openai.com/v1/chat/completions", ForceStream: true},
		Models: []Model{
			{ID: "gpt-5.4", Name: "GPT-5.4"},
			{ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"},
			{ID: "gpt-5", Name: "GPT-5"},
			{ID: "gpt-5-mini", Name: "GPT-5 Mini"},
			{ID: "gpt-4o", Name: "GPT-4o"},
			{ID: "gpt-4o-mini", Name: "GPT-4o Mini"},
			{ID: "gpt-4-turbo", Name: "GPT-4 Turbo"},
			{ID: "gpt-4.1", Name: "GPT-4.1"},
			{ID: "gpt-4.1-mini", Name: "GPT-4.1 Mini"},
			{ID: "o3", Name: "O3"},
			{ID: "o3-mini", Name: "O3 Mini"},
			{ID: "o4-mini", Name: "O4 Mini"},
			{ID: "o1", Name: "O1"},
			{ID: "o1-mini", Name: "O1 Mini"},
			{ID: "text-embedding-3-large", Name: "Text Embedding 3 Large", Kind: "embedding"},
			{ID: "text-embedding-3-small", Name: "Text Embedding 3 Small", Kind: "embedding"},
			{ID: "tts-1", Name: "TTS-1", Kind: "tts"},
			{ID: "tts-1-hd", Name: "TTS-1 HD", Kind: "tts"},
			{ID: "whisper-1", Name: "Whisper 1", Kind: "stt"},
			{ID: "gpt-image-1", Name: "GPT Image 1", Kind: "image"},
		},
		ServiceKinds: []string{"llm", "embedding", "tts", "stt", "image"},
	},
	{
		ID:       "claude",
		Priority: 10,
		Alias:    "cc",
		Display:  Display{Name: "Claude Code", Icon: "smart_toy", Color: "#D97757", Website: "https://claude.ai", Deprecated: true, DeprecNotice: "RISK_NOTICE"},
		Category: "oauth",
		Transport: Transport{
			BaseURL: "https://api.anthropic.com/v1/messages",
			Format:  "claude",
			Headers: map[string]string{
				"Anthropic-Version": "2023-06-01",
				"Anthropic-Beta":    "interleaved-thinking-2025-05-14,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advanced-tool-use-2025-11-20,effort-2025-11-24,structured-outputs-2025-12-15",
			},
			Auth: &AuthConfig{
				APIKey: &AuthStyle{Header: "x-api-key", Scheme: "raw"},
				OAuth:  &AuthStyle{Header: "Authorization", Scheme: "bearer"},
			},
			Quirks: &Quirks{CloakToolsOnOAuth: true},
		},
		Models: []Model{
			{ID: "claude-opus-4-8", Name: "Claude Opus 4.8"},
			{ID: "claude-sonnet-4-5-20250514", Name: "Claude Sonnet 4.5"},
			{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"},
			{ID: "claude-haiku-4-20250414", Name: "Claude Haiku 4"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "gemini",
		Priority: 50,
		HasFree:  true,
		Alias:    "gemini",
		Display:  Display{Name: "Gemini", Icon: "diamond", Color: "#4285F4", TextIcon: "GE", Website: "https://ai.google.dev", Notice: &Notice{APIKeyURL: "https://aistudio.google.com/app/apikey"}},
		Category: "freeTier",
		Transport: Transport{
			BaseURL: "https://generativelanguage.googleapis.com/v1beta/models",
			Format:  "gemini",
			Auth: &AuthConfig{
				APIKey: &AuthStyle{Header: "x-goog-api-key", Scheme: "raw"},
				OAuth:  &AuthStyle{Header: "Authorization", Scheme: "bearer"},
			},
		},
		Models: []Model{
			{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"},
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"},
			{ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash Lite"},
			{ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash"},
			{ID: "gemini-embedding-001", Name: "Gemini Embedding 001", Kind: "embedding"},
		},
		ServiceKinds: []string{"llm", "embedding", "image", "tts", "stt"},
	},
	{
		ID:       "anthropic",
		Priority: 20,
		Alias:    "anthropic",
		Display:  Display{Name: "Anthropic", Icon: "smart_toy", Color: "#D97757", Website: "https://console.anthropic.com"},
		Category: "apikey",
		Transport: Transport{
			BaseURL: "https://api.anthropic.com/v1/messages",
			Format:  "claude",
			Headers: map[string]string{
				"Anthropic-Version": "2023-06-01",
			},
			Auth: &AuthConfig{
				APIKey: &AuthStyle{Header: "x-api-key", Scheme: "raw"},
			},
		},
		Models: []Model{
			{ID: "claude-opus-4-20250514", Name: "Claude Opus 4"},
			{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"},
			{ID: "claude-haiku-4-20250414", Name: "Claude Haiku 4"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "deepseek",
		Priority: 40,
		Alias:    "ds",
		Display:  Display{Name: "DeepSeek", Icon: "psychology", Color: "#4D6BFE", TextIcon: "DS", Website: "https://platform.deepseek.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.deepseek.com/v1/chat/completions"},
		Models: []Model{
			{ID: "deepseek-chat", Name: "DeepSeek V3"},
			{ID: "deepseek-reasoner", Name: "DeepSeek R1"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "groq",
		Priority: 60,
		Alias:    "groq",
		Display:  Display{Name: "Groq", Icon: "bolt", Color: "#F55036", TextIcon: "GQ", Website: "https://console.groq.com"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "https://api.groq.com/openai/v1/chat/completions"},
		Models: []Model{
			{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B"},
			{ID: "llama-3.1-8b-instant", Name: "Llama 3.1 8B"},
			{ID: "mixtral-8x7b-32768", Name: "Mixtral 8x7B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "openrouter",
		Priority: 70,
		Alias:    "or",
		Display:  Display{Name: "OpenRouter", Icon: "hub", Color: "#6366F1", TextIcon: "OR", Website: "https://openrouter.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://openrouter.ai/api/v1/chat/completions"},
		Models: []Model{
			{ID: "anthropic/claude-sonnet-4", Name: "Claude Sonnet 4 (OR)"},
			{ID: "openai/gpt-4o", Name: "GPT-4o (OR)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "github",
		Priority: 15,
		Alias:    "gh",
		Display:  Display{Name: "GitHub Copilot", Icon: "code", Color: "#6e40c9", TextIcon: "GH", Website: "https://github.com/features/copilot"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.githubcopilot.com/v1/chat/completions"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Copilot)"},
			{ID: "claude-sonnet-4", Name: "Claude Sonnet 4 (Copilot)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "xai",
		Priority: 35,
		Alias:    "xai",
		Display:  Display{Name: "xAI", Icon: "smart_toy", Color: "#1DA1F2", TextIcon: "XA", Website: "https://console.x.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.x.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "grok-3", Name: "Grok 3"},
			{ID: "grok-3-mini", Name: "Grok 3 Mini"},
			{ID: "grok-3-fast", Name: "Grok 3 Fast"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "mistral",
		Priority: 45,
		Alias:    "mistral",
		Display:  Display{Name: "Mistral", Icon: "cloud", Color: "#FF7000", TextIcon: "MI", Website: "https://console.mistral.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.mistral.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "mistral-large-latest", Name: "Mistral Large"},
			{ID: "mistral-small-latest", Name: "Mistral Small"},
			{ID: "codestral-latest", Name: "Codestral"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "qwen",
		Priority: 55,
		Alias:    "qw",
		Display:  Display{Name: "Qwen", Icon: "psychology", Color: "#615EFC", TextIcon: "QW", Website: "https://dashscope.aliyun.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"},
		Models: []Model{
			{ID: "qwen-max", Name: "Qwen Max"},
			{ID: "qwen-plus", Name: "Qwen Plus"},
			{ID: "qwen-turbo", Name: "Qwen Turbo"},
			{ID: "qwen-long", Name: "Qwen Long"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "cohere",
		Priority: 65,
		Alias:    "co",
		Display:  Display{Name: "Cohere", Icon: "auto_awesome", Color: "#39594D", TextIcon: "CO", Website: "https://cohere.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.cohere.ai/v2/chat"},
		Models: []Model{
			{ID: "command-r-plus", Name: "Command R+"},
			{ID: "command-r", Name: "Command R"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "fireworks",
		Priority: 75,
		Alias:    "fw",
		Display:  Display{Name: "Fireworks", Icon: "local_fire_department", Color: "#FF6B35", TextIcon: "FW", Website: "https://fireworks.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.fireworks.ai/inference/v1/chat/completions"},
		Models: []Model{
			{ID: "accounts/fireworks/models/llama-v3p1-405b-instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "together",
		Priority: 76,
		Alias:    "tg",
		Display:  Display{Name: "Together", Icon: "group_work", Color: "#0EA5E9", TextIcon: "TG", Website: "https://together.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.together.xyz/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Llama-3.1-405B-Instruct-Turbo", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "ollama",
		Priority: 80,
		Alias:    "ol",
		Display:  Display{Name: "Ollama", Icon: "smart_toy", Color: "#FFFFFF", TextIcon: "OL", Website: "https://ollama.ai"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:11434/v1/chat/completions"},
		Models:  []Model{},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "azure",
		Priority: 25,
		Alias:    "az",
		Display:  Display{Name: "Azure OpenAI", Icon: "cloud", Color: "#0078D4", TextIcon: "AZ", Website: "https://azure.microsoft.com/ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT/chat/completions?api-version=2024-02-01"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Azure)"},
			{ID: "gpt-4-turbo", Name: "GPT-4 Turbo (Azure)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "google-pse",
		Priority: 90,
		Alias:    "gpse",
		Display:  Display{Name: "Google PSE", Icon: "search", Color: "#4285F4", TextIcon: "GP", Website: "https://programmablesearchengine.google.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://www.googleapis.com/customsearch/v1"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "brave-search",
		Priority: 91,
		Alias:    "brave",
		Display:  Display{Name: "Brave Search", Icon: "search", Color: "#FB542B", TextIcon: "BR", Website: "https://brave.com/search/api"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.search.brave.com/res/v1/web/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "serper",
		Priority: 92,
		Alias:    "srp",
		Display:  Display{Name: "Serper", Icon: "search", Color: "#4285F4", TextIcon: "SR", Website: "https://serper.dev"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://google.serper.dev/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "serpapi",
		Priority: 93,
		Alias:    "spapi",
		Display:  Display{Name: "SerpAPI", Icon: "search", Color: "#1A73E8", TextIcon: "SP", Website: "https://serpapi.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://serpapi.com/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "tavily",
		Priority: 94,
		Alias:    "tav",
		Display:  Display{Name: "Tavily", Icon: "search", Color: "#0EA5E9", TextIcon: "TV", Website: "https://tavily.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.tavily.com/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "exa",
		Priority: 95,
		Alias:    "exa",
		Display:  Display{Name: "Exa", Icon: "search", Color: "#7C3AED", TextIcon: "EX", Website: "https://exa.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.exa.ai/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "linkup",
		Priority: 96,
		Alias:    "lup",
		Display:  Display{Name: "Linkup", Icon: "search", Color: "#10B981", TextIcon: "LU", Website: "https://linkup.so"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.linkup.so/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "searxng",
		Priority: 97,
		Alias:    "sxng",
		Display:  Display{Name: "SearXNG", Icon: "search", Color: "#374151", TextIcon: "SX", Website: "https://docs.searxng.org"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:8888/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "searchapi",
		Priority: 98,
		Alias:    "sapi",
		Display:  Display{Name: "SearchAPI", Icon: "search", Color: "#2563EB", TextIcon: "SA", Website: "https://searchapi.io"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.searchapi.io/api/v1/search"},
		Models:   []Model{},
		ServiceKinds: []string{"search"},
	},
	{
		ID:       "firecrawl",
		Priority: 99,
		Alias:    "fc",
		Display:  Display{Name: "Firecrawl", Icon: "language", Color: "#FF6B35", TextIcon: "FC", Website: "https://firecrawl.dev"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.firecrawl.dev/v1/scrape"},
		Models:   []Model{},
		ServiceKinds: []string{"fetch"},
	},
	{
		ID:       "jina-reader",
		Priority: 100,
		Alias:    "jr",
		Display:  Display{Name: "Jina Reader", Icon: "language", Color: "#10B981", TextIcon: "JR", Website: "https://jina.ai/reader"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://r.jina.ai"},
		Models:   []Model{},
		ServiceKinds: []string{"fetch"},
	},
	{
		ID:       "jina-ai",
		Priority: 101,
		Alias:    "jai",
		Display:  Display{Name: "Jina AI", Icon: "language", Color: "#10B981", TextIcon: "JA", Website: "https://jina.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.jina.ai/v1"},
		Models:   []Model{},
		ServiceKinds: []string{"fetch"},
	},
	{
		ID:       "deepgram",
		Priority: 102,
		Alias:    "dg",
		Display:  Display{Name: "Deepgram", Icon: "mic", Color: "#1CC88A", TextIcon: "DG", Website: "https://deepgram.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.deepgram.com/v1/listen"},
		Models: []Model{
			{ID: "nova-2", Name: "Nova 2", Kind: "stt"},
			{ID: "nova-2-medical", Name: "Nova 2 Medical", Kind: "stt"},
		},
		ServiceKinds: []string{"stt"},
	},
	{
		ID:       "assemblyai",
		Priority: 103,
		Alias:    "aa",
		Display:  Display{Name: "AssemblyAI", Icon: "mic", Color: "#E54D2E", TextIcon: "AA", Website: "https://assemblyai.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.assemblyai.com/v2/transcript"},
		Models: []Model{
			{ID: "best", Name: "Best", Kind: "stt"},
			{ID: "nano", Name: "Nano", Kind: "stt"},
		},
		ServiceKinds: []string{"stt"},
	},
	{
		ID:       "edge-tts",
		Priority: 104,
		Alias:    "etts",
		Display:  Display{Name: "Edge TTS", Icon: "volume_up", Color: "#00BCF2", TextIcon: "ET", Website: "https://github.com/rany2/edge-tts"},
		Category: "freeTier",
		Transport: Transport{BaseURL: ""},
		Models: []Model{
			{ID: "en-US-AriaNeural", Name: "Aria (EN-US)", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "elevenlabs",
		Priority: 105,
		Alias:    "11",
		Display:  Display{Name: "ElevenLabs", Icon: "volume_up", Color: "#000000", TextIcon: "11", Website: "https://elevenlabs.io"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.elevenlabs.io/v1/text-to-speech"},
		Models: []Model{
			{ID: "eleven_multilingual_v2", Name: "Multilingual V2", Kind: "tts"},
			{ID: "eleven_monolingual_v1", Name: "Monolingual V1", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "google-tts",
		Priority: 106,
		Alias:    "gtts",
		Display:  Display{Name: "Google TTS", Icon: "volume_up", Color: "#4285F4", TextIcon: "GT", Website: "https://cloud.google.com/text-to-speech"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://texttospeech.googleapis.com/v1/text:synthesize"},
		Models: []Model{
			{ID: "en-US-Neural2-J", Name: "Neural2 J (EN-US)", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "black-forest-labs",
		Priority: 107,
		Alias:    "bfl",
		Display:  Display{Name: "Black Forest Labs", Icon: "image", Color: "#000000", TextIcon: "BF", Website: "https://blackforestlabs.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.bfl.ml/v1"},
		Models: []Model{
			{ID: "flux-1.1-pro", Name: "Flux 1.1 Pro", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "fal-ai",
		Priority: 108,
		Alias:    "fal",
		Display:  Display{Name: "fal AI", Icon: "image", Color: "#7C3AED", TextIcon: "FL", Website: "https://fal.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://fal.run"},
		Models: []Model{
			{ID: "fal-ai/flux-pro/v1.1", Name: "Flux Pro 1.1", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "recraft",
		Priority: 109,
		Alias:    "rc",
		Display:  Display{Name: "Recraft", Icon: "image", Color: "#000000", TextIcon: "RC", Website: "https://www.recraft.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://external.api.recraft.ai/v1"},
		Models: []Model{
			{ID: "recraft-v3", Name: "Recraft V3", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "stability-ai",
		Priority: 110,
		Alias:    "stb",
		Display:  Display{Name: "Stability AI", Icon: "image", Color: "#000000", TextIcon: "SA", Website: "https://stability.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.stability.ai/v2beta"},
		Models: []Model{
			{ID: "stable-image-ultra", Name: "Ultra", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "runwayml",
		Priority: 111,
		Alias:    "rw",
		Display:  Display{Name: "RunwayML", Icon: "video_call", Color: "#000000", TextIcon: "RW", Website: "https://runwayml.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.dev.runwayml.com/v1"},
		Models: []Model{
			{ID: "gen3a_turbo", Name: "Gen 3A Turbo", Kind: "video"},
		},
		ServiceKinds: []string{"video"},
	},
	{
		ID:       "voyage-ai",
		Priority: 112,
		Alias:    "voy",
		Display:  Display{Name: "Voyage AI", Icon: "text_fields", Color: "#000000", TextIcon: "VA", Website: "https://voyage.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.voyageai.com/v1/embeddings"},
		Models: []Model{
			{ID: "voyage-3", Name: "Voyage 3", Kind: "embedding"},
		},
		ServiceKinds: []string{"embedding"},
	},
	{
		ID:       "nebius",
		Priority: 113,
		Alias:    "nb",
		Display:  Display{Name: "Nebius", Icon: "cloud", Color: "#6366F1", TextIcon: "NB", Website: "https://nebius.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.studio.nebius.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Meta-Llama-3.1-405B-Instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "cerebras",
		Priority: 114,
		Alias:    "cb",
		Display:  Display{Name: "Cerebras", Icon: "psychology", Color: "#000000", TextIcon: "CB", Website: "https://cerebras.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.cerebras.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "llama-3.3-70b", Name: "Llama 3.3 70B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "chutes",
		Priority: 115,
		Alias:    "ch",
		Display:  Display{Name: "Chutes", Icon: "bolt", Color: "#10B981", TextIcon: "CH", Website: "https://chutes.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.chutes.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "featherless",
		Priority: 116,
		Alias:    "fl",
		Display:  Display{Name: "Featherless", Icon: "psychology", Color: "#000000", TextIcon: "FL", Website: "https://featherless.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.featherless.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "huggingface",
		Priority: 117,
		Alias:    "hf",
		Display:  Display{Name: "Hugging Face", Icon: "sentiment_satisfied", Color: "#FFD21E", TextIcon: "HF", Website: "https://huggingface.co"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api-inference.huggingface.co/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Llama-3.1-405B-Instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "hyperbolic",
		Priority: 118,
		Alias:    "hb",
		Display:  Display{Name: "Hyperbolic", Icon: "speed", Color: "#000000", TextIcon: "HB", Website: "https://hyperbolic.xyz"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.hyperbolic.xyz/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Meta-Llama-3.1-405B-Instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "nvidia",
		Priority: 119,
		Alias:    "nv",
		Display:  Display{Name: "NVIDIA", Icon: "memory", Color: "#76B900", TextIcon: "NV", Website: "https://build.nvidia.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://integrate.api.nvidia.com/v1/chat/completions"},
		Models: []Model{
			{ID: "meta/llama-3.1-405b-instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "siliconflow",
		Priority: 120,
		Alias:    "sf",
		Display:  Display{Name: "SiliconFlow", Icon: "cloud", Color: "#000000", TextIcon: "SF", Website: "https://siliconflow.cn"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.siliconflow.cn/v1/chat/completions"},
		Models: []Model{
			{ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "together-ai",
		Priority: 121,
		Alias:    "ta",
		Display:  Display{Name: "Together AI", Icon: "group_work", Color: "#0EA5E9", TextIcon: "TA", Website: "https://together.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.together.xyz/v1/chat/completions"},
		Models: []Model{
			{ID: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "venice",
		Priority: 122,
		Alias:    "vn",
		Display:  Display{Name: "Venice", Icon: "mask", Color: "#000000", TextIcon: "VN", Website: "https://venice.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.venice.ai/api/v1/chat/completions"},
		Models: []Model{
			{ID: "llama-3.3-70b", Name: "Llama 3.3 70B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "vercel-ai-gateway",
		Priority: 123,
		Alias:    "vag",
		Display:  Display{Name: "Vercel AI Gateway", Icon: "cloud", Color: "#000000", TextIcon: "VG", Website: "https://vercel.com/ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.vercel.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Vercel)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "volcengine-ark",
		Priority: 124,
		Alias:    "va",
		Display:  Display{Name: "VolcEngine Ark", Icon: "cloud", Color: "#FF4500", TextIcon: "VA", Website: "https://www.volcengine.com/product/ark"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"},
		Models: []Model{
			{ID: "doubao-1.5-pro-256k", Name: "Doubao 1.5 Pro 256K"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "glm",
		Priority: 125,
		Alias:    "glm",
		Display:  Display{Name: "GLM", Icon: "psychology", Color: "#4D6BFE", TextIcon: "GL", Website: "https://open.bigmodel.cn"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://open.bigmodel.cn/api/paas/v4/chat/completions"},
		Models: []Model{
			{ID: "glm-4-plus", Name: "GLM 4 Plus"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "moonshot",
		Priority: 126,
		Alias:    "ks",
		Display:  Display{Name: "Moonshot", Icon: "brightness_3", Color: "#000000", TextIcon: "KS", Website: "https://platform.moonshot.cn"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.moonshot.cn/v1/chat/completions"},
		Models: []Model{
			{ID: "moonshot-v1-128k", Name: "Moonshot V1 128K"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "minimax",
		Priority: 127,
		Alias:    "mm",
		Display:  Display{Name: "MiniMax", Icon: "smart_toy", Color: "#000000", TextIcon: "MM", Website: "https://www.minimaxi.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.minimax.chat/v1/text/chatcompletion_v2"},
		Models: []Model{
			{ID: "MiniMax-Text-01", Name: "MiniMax Text 01"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "iflow",
		Priority: 128,
		Alias:    "if",
		Display:  Display{Name: "iFlow", Icon: "water_drop", Color: "#000000", TextIcon: "IF", Website: "https://iflow.cn"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.iflow.cn/v1/chat/completions"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (iFlow)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "qoder",
		Priority: 129,
		Alias:    "qo",
		Display:  Display{Name: "Qoder", Icon: "code", Color: "#000000", TextIcon: "QO", Website: "https://qoder.ai"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.qoder.ai/v1/chat/completions"},
		Models: []Model{
			{ID: "qoder-chat", Name: "Qoder Chat"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "kiro",
		Priority: 130,
		Alias:    "kiro",
		Display:  Display{Name: "Kiro", Icon: "code", Color: "#FF9900", TextIcon: "KR", Website: "https://kiro.dev"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://kiro.dev/v1/chat/completions", Format: "kiro"},
		Models: []Model{
			{ID: "sonnet-5", Name: "Sonnet 5"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "cursor",
		Priority: 131,
		Alias:    "cr",
		Display:  Display{Name: "Cursor", Icon: "code", Color: "#000000", TextIcon: "CR", Website: "https://cursor.sh"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api2.cursor.sh/v1/chat/completions", Format: "cursor"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Cursor)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "antigravity",
		Priority: 132,
		Alias:    "ag",
		Display:  Display{Name: "Antigravity", Icon: "rocket_launch", Color: "#4285F4", TextIcon: "AG", Website: "https://antigravity.dev"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://generativelanguage.googleapis.com/v1beta/models", Format: "antigravity"},
		Models: []Model{
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash (AG)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "codex",
		Priority: 133,
		Alias:    "cx",
		Display:  Display{Name: "Codex", Icon: "code", Color: "#10A37F", TextIcon: "CX", Website: "https://chatgpt.com/codex"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://chatgpt.com/backend-api/codex", Format: "openai"},
		Models: []Model{
			{ID: "o4-mini", Name: "O4 Mini"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "gemini-cli",
		Priority: 134,
		Alias:    "gc",
		Display:  Display{Name: "Gemini CLI", Icon: "terminal", Color: "#4285F4", TextIcon: "GC", Website: "https://github.com/google-gemini/gemini-cli"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "https://generativelanguage.googleapis.com/v1beta/models", Format: "gemini-cli"},
		Models: []Model{
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "grok-cli",
		Priority: 135,
		Alias:    "gcli",
		Display:  Display{Name: "Grok CLI", Icon: "terminal", Color: "#1DA1F2", TextIcon: "GC", Website: "https://github.com/xai-org/grok-cli"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.x.ai/v1/chat/completions", Format: "grok-cli"},
		Models: []Model{
			{ID: "grok-3", Name: "Grok 3"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "grok-web",
		Priority: 136,
		Alias:    "gw",
		Display:  Display{Name: "Grok Web", Icon: "language", Color: "#1DA1F2", TextIcon: "GW", Website: "https://grok.com"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://grok.com/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "grok-3", Name: "Grok 3"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "perplexity-web",
		Priority: 137,
		Alias:    "pw",
		Display:  Display{Name: "Perplexity Web", Icon: "search", Color: "#000000", TextIcon: "PW", Website: "https://perplexity.ai"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.perplexity.ai/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "sonar-pro", Name: "Sonar Pro"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "perplexity",
		Priority: 138,
		Alias:    "px",
		Display:  Display{Name: "Perplexity", Icon: "search", Color: "#20B2AA", TextIcon: "PX", Website: "https://perplexity.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.perplexity.ai/chat/completions"},
		Models: []Model{
			{ID: "sonar-pro", Name: "Sonar Pro"},
			{ID: "sonar", Name: "Sonar"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "ollama-local",
		Priority: 139,
		Alias:    "olc",
		Display:  Display{Name: "Ollama Local", Icon: "smart_toy", Color: "#FFFFFF", TextIcon: "OL", Website: "https://ollama.ai"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:11434/api/chat"},
		Models:  []Model{},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "commandcode",
		Priority: 140,
		Alias:    "cc",
		Display:  Display{Name: "CommandCode", Icon: "code", Color: "#000000", TextIcon: "CC", Website: "https://commandcode.dev"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.commandcode.dev/v1/chat/completions", Format: "commandcode"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (CC)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "xiaomi-tokenplan",
		Priority: 141,
		Alias:    "xt",
		Display:  Display{Name: "Xiaomi Tokenplan", Icon: "phone_android", Color: "#FF6900", TextIcon: "XT", Website: "https://xiaoai.mi.com"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.xiaoai.mi.com/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "MiMo-7B-RL", Name: "MiMo 7B RL"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "mimo-free",
		Priority: 142,
		Alias:    "mf",
		Display:  Display{Name: "MiMo Free", Icon: "smart_toy", Color: "#FF6900", TextIcon: "MF", Website: "https://mimo.free"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "https://api.mimo.free/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "MiMo-7B-RL", Name: "MiMo 7B RL"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "codebuddy-cn",
		Priority: 143,
		Alias:    "cbc",
		Display:  Display{Name: "CodeBuddy CN", Icon: "code", Color: "#000000", TextIcon: "CB", Website: "https://codebuddy.cn"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.codebuddy.cn/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (CodeBuddy)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "kimchi",
		Priority: 144,
		Alias:    "km",
		Display:  Display{Name: "Kimchi", Icon: "smart_toy", Color: "#000000", TextIcon: "KM", Website: "https://kimchi.ai"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.kimchi.ai/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Kimchi)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "kimi",
		Priority: 145,
		Alias:    "kimi",
		Display:  Display{Name: "Kimi", Icon: "smart_toy", Color: "#000000", TextIcon: "KI", Website: "https://kimi.moonshot.cn"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.moonshot.cn/v1/chat/completions"},
		Models: []Model{
			{ID: "moonshot-v1-128k", Name: "Kimi 128K"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "kilocode",
		Priority: 146,
		Alias:    "kl",
		Display:  Display{Name: "KiloCode", Icon: "code", Color: "#000000", TextIcon: "KL", Website: "https://kilocode.ai"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.kilocode.ai/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (KiloCode)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "cline",
		Priority: 147,
		Alias:    "cl",
		Display:  Display{Name: "Cline", Icon: "code", Color: "#000000", TextIcon: "CL", Website: "https://cline.bot"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.cline.bot/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (Cline)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "clinepass",
		Priority: 148,
		Alias:    "clp",
		Display:  Display{Name: "ClinePass", Icon: "code", Color: "#000000", TextIcon: "CP", Website: "https://clinepass.com"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.clinepass.com/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (ClinePass)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "gitlab",
		Priority: 149,
		Alias:    "gl",
		Display:  Display{Name: "GitLab", Icon: "code", Color: "#FC6D26", TextIcon: "GL", Website: "https://gitlab.com"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://gitlab.com/api/v4/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "gpt-4o", Name: "GPT-4o (GitLab)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "blackbox",
		Priority: 150,
		Alias:    "bb",
		Display:  Display{Name: "Blackbox", Icon: "smart_toy", Color: "#000000", TextIcon: "BB", Website: "https://blackbox.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.blackbox.ai/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "blackbox-large", Name: "Blackbox Large"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "youcom",
		Priority: 151,
		Alias:    "yc",
		Display:  Display{Name: "You.com", Icon: "search", Color: "#000000", TextIcon: "YC", Website: "https://you.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.you.com/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "yougpt", Name: "YouGPT"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "perplexity-agent",
		Priority: 152,
		Alias:    "pa",
		Display:  Display{Name: "Perplexity Agent", Icon: "smart_toy", Color: "#000000", TextIcon: "PA", Website: "https://perplexity.ai"},
		Category: "oauth",
		Transport: Transport{BaseURL: "https://api.perplexity.ai/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "sonar-pro", Name: "Sonar Pro"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "opencode",
		Priority: 153,
		Alias:    "oc",
		Display:  Display{Name: "OpenCode", Icon: "code", Color: "#000000", TextIcon: "OC", Website: "https://opencode.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.opencode.ai/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "mimo-v2-free", Name: "MiMo V2 Free"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "opencode-go",
		Priority: 154,
		Alias:    "ocg",
		Display:  Display{Name: "OpenCode Go", Icon: "code", Color: "#00A98C", TextIcon: "OG", Website: "https://opencode.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.opencode.ai/v1/chat/completions", Format: "openai"},
		Models: []Model{
			{ID: "mimo-v2-free", Name: "MiMo V2 Free"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "glm-cn",
		Priority: 155,
		Alias:    "gc",
		Display:  Display{Name: "GLM CN", Icon: "psychology", Color: "#4D6BFE", TextIcon: "GC", Website: "https://open.bigmodel.cn"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://open.bigmodel.cn/api/paas/v4/chat/completions"},
		Models: []Model{
			{ID: "glm-4-plus", Name: "GLM 4 Plus"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "minimax-cn",
		Priority: 156,
		Alias:    "mmc",
		Display:  Display{Name: "MiniMax CN", Icon: "smart_toy", Color: "#000000", TextIcon: "MC", Website: "https://www.minimaxi.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.minimax.chat/v1/text/chatcompletion_v2"},
		Models: []Model{
			{ID: "MiniMax-Text-01", Name: "MiniMax Text 01"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "alicode",
		Priority: 157,
		Alias:    "ac",
		Display:  Display{Name: "AliCode", Icon: "code", Color: "#FF6A00", TextIcon: "AC", Website: "https://alibaba.com/code"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"},
		Models: []Model{
			{ID: "qwen-max", Name: "Qwen Max"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "alicode-intl",
		Priority: 158,
		Alias:    "aci",
		Display:  Display{Name: "AliCode Intl", Icon: "code", Color: "#FF6A00", TextIcon: "AI", Website: "https://alibaba.com/code/intl"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"},
		Models: []Model{
			{ID: "qwen-max", Name: "Qwen Max"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "xiaomi-mimo",
		Priority: 159,
		Alias:    "xm",
		Display:  Display{Name: "Xiaomi MiMo", Icon: "phone_android", Color: "#FF6900", TextIcon: "XM", Website: "https://xiaoai.mi.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.xiaoai.mi.com/v1/chat/completions"},
		Models: []Model{
			{ID: "MiMo-7B-RL", Name: "MiMo 7B RL"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "mmf",
		Priority: 160,
		Alias:    "mmf",
		Display:  Display{Name: "MMF", Icon: "smart_toy", Color: "#000000", TextIcon: "MF", Website: "https://mmf.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.mmf.com/v1/chat/completions"},
		Models:  []Model{},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "nanobanana",
		Priority: 161,
		Alias:    "nb",
		Display:  Display{Name: "Nanobanana", Icon: "smart_toy", Color: "#000000", TextIcon: "NB", Website: "https://nanobanana.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.nanobanana.ai/v1/chat/completions"},
		Models:  []Model{},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "byteplus",
		Priority: 162,
		Alias:    "bp",
		Display:  Display{Name: "BytePlus", Icon: "cloud", Color: "#000000", TextIcon: "BP", Website: "https://byteplus.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.byteplus.com/v1/chat/completions"},
		Models:  []Model{},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "cloudflare-ai",
		Priority: 163,
		Alias:    "cf",
		Display:  Display{Name: "Cloudflare AI", Icon: "cloud", Color: "#F38020", TextIcon: "CF", Website: "https://developers.cloudflare.com/workers-ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT/ai/v1/chat/completions"},
		Models: []Model{
			{ID: "@cf/meta/llama-3.1-405b-instruct", Name: "Llama 3.1 405B"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "inworld",
		Priority: 164,
		Alias:    "iw",
		Display:  Display{Name: "Inworld", Icon: "smart_toy", Color: "#000000", TextIcon: "IW", Website: "https://inworld.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.inworld.ai/v1/chat/completions"},
		Models:  []Model{},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "cartesia",
		Priority: 165,
		Alias:    "ct",
		Display:  Display{Name: "Cartesia", Icon: "volume_up", Color: "#000000", TextIcon: "CT", Website: "https://cartesia.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.cartesia.ai/v1/tts"},
		Models: []Model{
			{ID: "sonic-2", Name: "Sonic 2", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "playht",
		Priority: 166,
		Alias:    "ph",
		Display:  Display{Name: "PlayHT", Icon: "volume_up", Color: "#000000", TextIcon: "PH", Website: "https://play.ht"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.play.ht/v1/tts"},
		Models: []Model{
			{ID: "play-2.0", Name: "Play 2.0", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "coqui",
		Priority: 167,
		Alias:    "cq",
		Display:  Display{Name: "Coqui", Icon: "volume_up", Color: "#000000", TextIcon: "CQ", Website: "https://coqui.ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.coqui.ai/v1/tts"},
		Models: []Model{
			{ID: "tts-1", Name: "TTS 1", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "tortoise",
		Priority: 168,
		Alias:    "tt",
		Display:  Display{Name: "Tortoise", Icon: "volume_up", Color: "#000000", TextIcon: "TT", Website: "https://github.com/neonbjb/tortoise-tts"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:8000/v1/tts"},
		Models: []Model{
			{ID: "tortoise", Name: "Tortoise", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "aws-polly",
		Priority: 169,
		Alias:    "ap",
		Display:  Display{Name: "AWS Polly", Icon: "volume_up", Color: "#FF9900", TextIcon: "AP", Website: "https://aws.amazon.com/polly"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://polly.us-east-1.amazonaws.com/v1/speech"},
		Models: []Model{
			{ID: "Joanna", Name: "Joanna", Kind: "tts"},
		},
		ServiceKinds: []string{"tts"},
	},
	{
		ID:       "sdwebui",
		Priority: 170,
		Alias:    "sdu",
		Display:  Display{Name: "Stable Diffusion WebUI", Icon: "image", Color: "#000000", TextIcon: "SD", Website: "https://github.com/AUTOMATIC1111/stable-diffusion-webui"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:7860/sdapi/v1/txt2img"},
		Models: []Model{
			{ID: "sd-xl", Name: "SD XL", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "comfyui",
		Priority: 171,
		Alias:    "cu",
		Display:  Display{Name: "ComfyUI", Icon: "image", Color: "#000000", TextIcon: "CU", Website: "https://github.com/comfyanonymous/ComfyUI"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "http://localhost:8188/api/v1/txt2img"},
		Models: []Model{
			{ID: "sdxl", Name: "SDXL", Kind: "image"},
		},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "topaz",
		Priority: 172,
		Alias:    "tz",
		Display:  Display{Name: "Topaz", Icon: "image", Color: "#000000", TextIcon: "TZ", Website: "https://topazlabs.com"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://api.topazlabs.com/v1/image"},
		Models:  []Model{},
		ServiceKinds: []string{"image"},
	},
	{
		ID:       "vertex",
		Priority: 22,
		Alias:    "vx",
		Display:  Display{Name: "Vertex AI", Icon: "cloud", Color: "#4285F4", TextIcon: "VX", Website: "https://cloud.google.com/vertex-ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://us-central1-aiplatform.googleapis.com/v1/projects/YOUR_PROJECT/locations/us-central1/publishers/google/models", Format: "vertex"},
		Models: []Model{
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"},
			{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "vertex-partner",
		Priority: 23,
		Alias:    "vxp",
		Display:  Display{Name: "Vertex Partner", Icon: "cloud", Color: "#4285F4", TextIcon: "VP", Website: "https://cloud.google.com/vertex-ai"},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://us-central1-aiplatform.googleapis.com/v1/projects/YOUR_PROJECT/locations/us-central1/publishers", Format: "vertex"},
		Models: []Model{
			{ID: "anthropic.claude-sonnet-4-20250514", Name: "Claude Sonnet 4 (Vertex)"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "alims-intl",
		Priority: 11,
		Alias:    "alims-intl",
		Display:  Display{Name: "Alibaba Studio", Icon: "cloud", Color: "#FF6A00", TextIcon: "ALi", Website: "https://modelstudio.console.alibabacloud.com", Notice: &Notice{APIKeyURL: "https://modelstudio.console.alibabacloud.com/?apiKey=1"}},
		Category: "apikey",
		Transport: Transport{BaseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions"},
		Models: []Model{
			{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"},
			{ID: "kimi-k2.5", Name: "Kimi K2.5"},
			{ID: "glm-5", Name: "GLM 5"},
			{ID: "MiniMax-M2.5", Name: "MiniMax M2.5"},
			{ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"},
			{ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"},
			{ID: "glm-4.7", Name: "GLM 4.7"},
		},
		ServiceKinds: []string{"llm"},
	},
	{
		ID:       "local-device",
		Priority: 173,
		Alias:    "local-device",
		Display:  Display{Name: "Local Device", Icon: "speaker", Color: "#64748B", TextIcon: "LD"},
		Category: "freeTier",
		Transport: Transport{BaseURL: "local-device", Format: "local-device"},
		Models:       []Model{},
		ServiceKinds: []string{"tts"},
	},
}

var (
	providerMap      = map[string]*Provider{}
	providerAliasMap = map[string]string{}
)

func init() {
	for i := range Registry {
		p := &Registry[i]
		providerMap[p.ID] = p
		if p.Alias != "" {
			providerAliasMap[p.Alias] = p.ID
		}
		for _, m := range p.Models {
			_ = m
		}
	}
	providerAliasMap["oa"] = "openai"
}

func GetProvider(id string) *Provider {
	if p, ok := providerMap[id]; ok {
		return p
	}
	return nil
}

func GetProviderByAlias(alias string) *Provider {
	if id, ok := providerAliasMap[alias]; ok {
		return GetProvider(id)
	}
	for _, p := range Registry {
		if p.Alias == alias {
			return &p
		}
	}
	return nil
}

func ResolveAlias(aliasOrID string) string {
	if id, ok := providerAliasMap[aliasOrID]; ok {
		return id
	}
	if p := GetProvider(aliasOrID); p != nil {
		return p.ID
	}
	return aliasOrID
}

func ProviderAliases() map[string]string {
	res := make(map[string]string, len(providerAliasMap))
	for k, v := range providerAliasMap {
		res[k] = v
	}
	return res
}

func ListProviders() []Provider {
	return Registry
}
